#!/bin/bash

cd $(dirname $0)/../dist/moby

if [ "1" == "2" ]; then
  linuxkit run -mem 2048 rancheros
else
  qemu-system-x86_64 \
      -nographic \
      -kernel ./rancheros-kernel \
      -initrd ./rancheros-initrd.img \
      -m 2048 \
      -device virtio-rng-pci \
      -smp 1 \
      -enable-kvm \
      -machine q35,accel=kvm:tcg \
      -net nic,vlan=0,model=virtio \
      -net user,vlan=0,hostfwd=tcp::3333-:22,hostname=maxive-moby \
      -append 'printk.devkmsg=on maxive.debug=true maxive.password=maxive console=ttyS0 maxive.autologin=ttyS0 console=tty0 maxive.autologin=tty0 console=tty1 maxive.autologin=tty1 maxive.state.dev=LABEL=RANCHER_STATE maxive.state.autoformat=[/dev/sda,/dev/vda] maxive.rm_usr' 
fi
